import Head from 'next/head'
import type { GetStaticProps } from 'next'
import Header from '../components/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import WorkExperience from '../components/WorkExperience'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import ContactMe from '../components/ContactMe'
import Link from 'next/link'
import { Experience, PageInfo, Project, Skill, Social } from '../typings'
import { fetchPageInfo } from '../utils/fetchPageInfo'
import { fetchExperiences } from '../utils/fetchExperiences'
import { fetchProjects } from '../utils/fetchProjects'
import { fetchSkills } from '../utils/fetchSkills'
import { fetchSocials } from '../utils/fetchSocial'
type Props = {
  pageInfo: PageInfo;
  experiences: Experience[];
  skills: Skill[];
  projects: Project[];
  socials: Social[];

}


const Home =({pageInfo, experiences, skills, projects, socials}: Props) => {  
  return (
    <div className='bg-[rgb(36,35,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80'> 
         <Head>
        <title>Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header socials={socials}/>
      <section id='hero' className='snap-start'>
        <Hero pageInfo={pageInfo}/>

      </section>
      <section id="about" className='snap-center'>
        <About />
      </section>
      <section id="experience" className='snap-center'>
        <WorkExperience />

      </section>
      <section id='skills' className='snap-start'>
        <Skills />

      </section>
      <section id="projects" className='snap-start'>
        <Projects />
      </section>


      {/* CONTACT ME */}
      <section id='contact' className='snap-start'>
        <ContactMe />

      </section>
      
    </div>
  )
}
export default Home;
export const getStaticProps: GetStaticProps<Props> = async () => {
  const pageInfo: PageInfo = await fetchPageInfo();
  const experiences:  Experience[] = await fetchExperiences();
  const skills: Skill[] = await fetchSkills();
  const projects: Project[] = await fetchProjects();
const socials: Social[] = await fetchSocials();
return {
  props: {
    pageInfo,
    experiences,
    skills,
    projects,
    socials,

  },
  revalidate: 10,
}


}